version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: pts3-php
    volumes:
      - "./:/var/www/html/"
      - symfonyvar:/var/www/html/projet/var
      - symfonyvendor:/var/www/html/projet/vendor
  web:
    container_name: pts3-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8888:80"
      - "8887:81"
    volumes:
      - "./:/var/www/html/"
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: pts3-db
    ports:
      - "3307:3306" # mysql
    environment:
      MYSQL_DATABASE: iut
      MYSQL_USER: iut
      MYSQL_PASSWORD: iut
      MYSQL_ROOT_PASSWORD: iut
  maildev:
    image: maildev/maildev
    container_name: pts3-maildevProjet
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always


volumes:
  symfonyvar:
  symfonyvendor:
