vich_uploader:
    db_driver: orm

    mappings:
        publication_image:
            uri_prefix: '%publication_images%'
            upload_destination: '%kernel.project_dir%/public%publication_images%'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

        publication_pdf:
            uri_prefix: '%publication_pdf%'
            upload_destination: '%kernel.project_dir%/public%publication_pdf%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
