vich_uploader:
  db_driver: orm

  mappings:
    publication_image:
      uri_prefix: '%publication_images%'
      upload_destination: '%kernel.project_dir%/public%publication_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    publication_pdf:
      uri_prefix: '%publication_pdf%'
      upload_destination: '%kernel.project_dir%/public%publication_pdf%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    person_image:
      uri_prefix: '%person_images%'
      upload_destination: '%kernel.project_dir%/public%person_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    article_image:
      uri_prefix: '%article_images%'
      upload_destination: '%kernel.project_dir%/public%article_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    article_pdf:
      uri_prefix: '%article_pdf%'
      upload_destination: '%kernel.project_dir%/public%article_pdf%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
